{
  "language": "c++",
  "os": "linux",
  "compiler": "gcc",
  "addons": {
    "sources": [
      "livm-toolchain-precise",
      "ubuntu-toolchain-r-test"
    ],
    "packages": [
      "cmake",
      "cmake-data",
      "g++-5",
      "gcc-5"
    ]
  },
  "before_script": [
    "mkdir build",
    "cd build",
    "cmake .."
  ],
  "script": [
    "cmake --build ."
  ]
}