{
  "language": "c++",
  "os": "linux",
  "compiler": "gcc",
  "addons": {
    "sources": [
      "livm-toolchain-precise",
      "ubuntu-toolchain-r-test"
    ],
    "packages": [
      "cmake",
      "cmake-data",
      "g++-6",
      "gcc-6"
    ]
  },
  "before_install": [
    "export CXX=\"g++-6\" CC=\"gcc-6\""
  ],
  "before_script": [
    "mkdir build",
    "cd build",
    "cmake .."
  ],
  "script": [
    "cmake --build ."
  ]
}