{
  "language": "c++",
  "os": "linux",
  "dist": "precise",
  "compiler": "gcc",
  "banches": {
    "except": ["gh-pages"]
  },
  "env": {
    "global": {
      "GH_REPO_NAME": "blatt-2-sudoku07-1",
      "DOXYFILE": "doxyfile.txt",
      "GH_REPO_REF": "github.com/algdat/blatt-2-sudoku07-1.git"
    }
  },
  "addons": {
    "apt": {
      "sources": [
        "george-edison55-precise-backports",
        "ubuntu-toolchain-r-test"
      ],
      "packages": [
        "cmake",
        "cmake-data",
        "g++-6",
        "gcc-6",
        "doxygen",
        "doxygen-doc",
        "doxygen-latex",
        "doxygen-gui",
        "graphviz"
      ]
    }
  },
  "before_install": [
    "export CXX=\"g++-6\" CC=\"gcc-6\""
  ],
  "before_script": [
    "mkdir build",
    "cd build",
    "cmake .."
  ],
  "script": [
    "cmake --build .",
    "cd test",
    "ls",	
    "./sudokuTest"
  ],
  "after_success": [
    "cd $TRAVIS_BUILD_DIR",
    "chmod +x generateDocumentationAndDeploy.sh",
    "./generateDocumentationAndDeploy.sh"
  ]
}