{
  "language": "c++",
  "os": "linux",
  "compiler": "gcc",
  "addons": {
    "packages": [
      "cmake",
      "cmake-data"
    ]
  },
  "before_script": [
    "mkdir build",
    "cd build",
    "cmake .."
  ],
  "script": [
    "cmake --build ."
  ]
}